feat: Move changes my-dev and my-rel
Instead of changing "bases".

No size change:

  $ ./mke
  -rwxr-xr-x 2 wink users 611K Nov 12 10:49 target/my-dev/exper-refcell
  -rwxr-xr-x 2 wink users 279K Nov 12 10:49 target/my-rel/exper-refcell
     Compiling exper-refcell v0.1.0 (/home/wink/prgs/rust/myrepos/exper-refcell)
      Finished my-dev [unoptimized + debuginfo] target(s) in 1.65s
       Running `target/my-dev/exper-refcell`
  thread 'main' panicked at 'explicit panic', src/main.rs:53:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     Compiling exper-refcell v0.1.0 (/home/wink/prgs/rust/myrepos/exper-refcell)
      Finished my-rel [optimized] target(s) in 2.23s
       Running `target/my-rel/exper-refcell`
  -rwxr-xr-x 2 wink users 611K Nov 12 10:54 target/my-dev/exper-refcell
  -rwxr-xr-x 2 wink users 279K Nov 12 10:54 target/my-rel/exper-refcell