feat: Reduce size of executable, strop
Set strip = true

Size dropped from 3.9M to 311K:

   $ ls -lrth target/*/exper-refcell
   -rwxr-xr-x 2 wink users 3.9M Nov 12 10:24 target/my-dev/exper-refcell
   -rwxr-xr-x 2 wink users 3.9M Nov 12 10:24 target/my-rel/exper-refcell
   wink@fwlaptop 22-11-12T18:25:24.300Z:~/prgs/rust/myrepos/exper-refcell (use-refcell-maybe-uninit)
   $ cargo run --profile my-dev
      Compiling exper-refcell v0.1.0 (/home/wink/prgs/rust/myrepos/exper-refcell)
       Finished my-dev [unoptimized + debuginfo] target(s) in 0.11s
        Running `target/my-dev/exper-refcell`
   thread 'main' panicked at 'explicit panic', src/main.rs:53:5
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   wink@fwlaptop 22-11-12T18:25:30.078Z:~/prgs/rust/myrepos/exper-refcell (use-refcell-maybe-uninit)
   $ cargo run --profile my-rel
      Compiling exper-refcell v0.1.0 (/home/wink/prgs/rust/myrepos/exper-refcell)
       Finished my-rel [optimized] target(s) in 0.11s
        Running `target/my-rel/exper-refcell`
   wink@fwlaptop 22-11-12T18:25:50.053Z:~/prgs/rust/myrepos/exper-refcell (use-refcell-maybe-uninit)
   $ ls -lrth target/*/exper-refcell
   -rwxr-xr-x 2 wink users 311K Nov 12 10:25 target/my-dev/exper-refcell
   -rwxr-xr-x 2 wink users 311K Nov 12 10:25 target/my-rel/exper-refcell
   wink@fwlaptop 22-11-12T18:26:01.657Z:~/prgs/rust/myrepos/exper-refcell (use-refcell-maybe-uninit)